// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIkkKEVRyYW5zY3JpYmVSZXF1ZXN0EjQKBWF1ZGlvGAEgASgLMiAubWVtb3MuYXBpLnYxLlRyYW5zY3JpcHRpb25BdWRpb0ID4EECIncKElRyYW5zY3JpcHRpb25BdWRpbxIWCgdjb250ZW50GAEgASgMQgPgQQRIABINCgN1cmkYAiABKAlIABIVCghmaWxlbmFtZRgDIAEoCUID4EEBEhkKDGNvbnRlbnRfdHlwZRgEIAEoCUID4EEBQggKBnNvdXJjZSIiChJUcmFuc2NyaWJlUmVzcG9uc2USDAoEdGV4dBgBIAEoCSImChFTeW50aGVzaXplUmVxdWVzdBIRCgR0ZXh0GAEgASgJQgPgQQIiOQoSU3ludGhlc2l6ZVJlc3BvbnNlEg0KBWF1ZGlvGAEgASgMEhQKDGNvbnRlbnRfdHlwZRgCIAEoCSI8Cg9Db21wbGV0ZVJlcXVlc3QSEwoGcHJvbXB0GAEgASgJQgPgQQISFAoHY29udGVudBgCIAEoCUID4EEBIiAKEENvbXBsZXRlUmVzcG9uc2USDAoEdGV4dBgBIAEoCTL0AgoJQUlTZXJ2aWNlEnkKClRyYW5zY3JpYmUSHy5tZW1vcy5hcGkudjEuVHJhbnNjcmliZVJlcXVlc3QaIC5tZW1vcy5hcGkudjEuVHJhbnNjcmliZVJlc3BvbnNlIijaQQVhdWRpb4LT5JMCGjoBKiIVL2FwaS92MS9haTp0cmFuc2NyaWJlEngKClN5bnRoZXNpemUSHy5tZW1vcy5hcGkudjEuU3ludGhlc2l6ZVJlcXVlc3QaIC5tZW1vcy5hcGkudjEuU3ludGhlc2l6ZVJlc3BvbnNlIifaQQR0ZXh0gtPkkwIaOgEqIhUvYXBpL3YxL2FpOnN5bnRoZXNpemUScgoIQ29tcGxldGUSHS5tZW1vcy5hcGkudjEuQ29tcGxldGVSZXF1ZXN0Gh4ubWVtb3MuYXBpLnYxLkNvbXBsZXRlUmVzcG9uc2UiJ9pBBnByb21wdILT5JMCGDoBKiITL2FwaS92MS9haTpjb21wbGV0ZUKmAQoQY29tLm1lbW9zLmFwaS52MUIOQWlTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.TranscribeRequest
 */
export type TranscribeRequest = Message<"memos.api.v1.TranscribeRequest"> & {
  /**
   * Required. Audio input.
   *
   * @generated from field: memos.api.v1.TranscriptionAudio audio = 1;
   */
  audio?: TranscriptionAudio | undefined;
};

/**
 * Describes the message memos.api.v1.TranscribeRequest.
 * Use `create(TranscribeRequestSchema)` to create a new message.
 */
export const TranscribeRequestSchema: GenMessage<TranscribeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.TranscriptionAudio
 */
export type TranscriptionAudio = Message<"memos.api.v1.TranscriptionAudio"> & {
  /**
   * @generated from oneof memos.api.v1.TranscriptionAudio.source
   */
  source: {
    /**
     * Inline audio bytes.
     *
     * @generated from field: bytes content = 1;
     */
    value: Uint8Array;
    case: "content";
  } | {
    /**
     * URI for audio content. Reserved for future use.
     *
     * @generated from field: string uri = 2;
     */
    value: string;
    case: "uri";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. The uploaded filename.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Optional. The MIME type of the input audio.
   *
   * @generated from field: string content_type = 4;
   */
  contentType: string;
};

/**
 * Describes the message memos.api.v1.TranscriptionAudio.
 * Use `create(TranscriptionAudioSchema)` to create a new message.
 */
export const TranscriptionAudioSchema: GenMessage<TranscriptionAudio> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from message memos.api.v1.TranscribeResponse
 */
export type TranscribeResponse = Message<"memos.api.v1.TranscribeResponse"> & {
  /**
   * The transcribed text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.TranscribeResponse.
 * Use `create(TranscribeResponseSchema)` to create a new message.
 */
export const TranscribeResponseSchema: GenMessage<TranscribeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 2);

/**
 * @generated from message memos.api.v1.SynthesizeRequest
 */
export type SynthesizeRequest = Message<"memos.api.v1.SynthesizeRequest"> & {
  /**
   * Required. Text to convert to speech.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.SynthesizeRequest.
 * Use `create(SynthesizeRequestSchema)` to create a new message.
 */
export const SynthesizeRequestSchema: GenMessage<SynthesizeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 3);

/**
 * @generated from message memos.api.v1.SynthesizeResponse
 */
export type SynthesizeResponse = Message<"memos.api.v1.SynthesizeResponse"> & {
  /**
   * Generated audio bytes.
   *
   * @generated from field: bytes audio = 1;
   */
  audio: Uint8Array;

  /**
   * MIME type of the generated audio, e.g. "audio/mpeg".
   *
   * @generated from field: string content_type = 2;
   */
  contentType: string;
};

/**
 * Describes the message memos.api.v1.SynthesizeResponse.
 * Use `create(SynthesizeResponseSchema)` to create a new message.
 */
export const SynthesizeResponseSchema: GenMessage<SynthesizeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 4);

/**
 * @generated from message memos.api.v1.CompleteRequest
 */
export type CompleteRequest = Message<"memos.api.v1.CompleteRequest"> & {
  /**
   * Required. The user instruction for this turn (e.g. "polish this paragraph").
   *
   * @generated from field: string prompt = 1;
   */
  prompt: string;

  /**
   * Optional. Source text to transform — usually the editor selection, or the
   * whole draft when no selection exists.
   *
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message memos.api.v1.CompleteRequest.
 * Use `create(CompleteRequestSchema)` to create a new message.
 */
export const CompleteRequestSchema: GenMessage<CompleteRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 5);

/**
 * @generated from message memos.api.v1.CompleteResponse
 */
export type CompleteResponse = Message<"memos.api.v1.CompleteResponse"> & {
  /**
   * The model's reply text. Writing-assistant responses are plain markdown.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.CompleteResponse.
 * Use `create(CompleteResponseSchema)` to create a new message.
 */
export const CompleteResponseSchema: GenMessage<CompleteResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 6);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * Transcribe transcribes an audio file using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.Transcribe
   */
  transcribe: {
    methodKind: "unary";
    input: typeof TranscribeRequestSchema;
    output: typeof TranscribeResponseSchema;
  },
  /**
   * Synthesize converts text to speech audio using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.Synthesize
   */
  synthesize: {
    methodKind: "unary";
    input: typeof SynthesizeRequestSchema;
    output: typeof SynthesizeResponseSchema;
  },
  /**
   * Complete runs one writing-assistant turn against an OpenAI-compatible
   * chat-completions endpoint configured on the instance.
   *
   * @generated from rpc memos.api.v1.AIService.Complete
   */
  complete: {
    methodKind: "unary";
    input: typeof CompleteRequestSchema;
    output: typeof CompleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

